-- ================================================================================
-- HIS System - 测试数据迁移脚本
-- ================================================================================
-- Version: V6
-- Description: 为HIS系统插入符合所有约束的测试数据
-- Author: HIS Development Team
-- Date: 2025-01-03
-- ================================================================================
--
-- 数据包含:
-- - 18个系统用户 (1管理员 + 13医生 + 2护士 + 1药师 + 1收费员)
-- - 7个科室 (内科、外科、儿科、妇产科、眼科、耳鼻喉科、急诊科)
-- - 13个医生 (分布在各个科室)
-- - 10个患者 (包含完整的人口统计信息)
-- - 21种药品 (包含定价和库存信息)
-- - 10个挂号记录 (5个今天, 5个昨天)
-- - 5个病历记录 (已完成的就诊)
-- - 8个处方 (包含21个处方明细)
-- - 13个收费记录
--
-- 密码说明: 所有用户密码使用BCrypt加密，哈希值对应明文密码 "admin123"
--
-- ================================================================================

-- ============================================
-- 临时修改identity列为BY DEFAULT模式，允许显式插入ID
-- ============================================

-- 1. 修改Department表
ALTER TABLE his_department ALTER COLUMN main_id SET GENERATED BY DEFAULT;
INSERT INTO his_department (main_id, dept_code, name, parent_id, sort_order, description, status)
VALUES
    (1, 'DEPT_INTERNAL', '内科', NULL, 1, '内科诊疗科室', 1),
    (2, 'DEPT_SURGERY', '外科', NULL, 2, '外科诊疗科室', 1),
    (3, 'DEPT_PEDIATRICS', '儿科', NULL, 3, '儿科诊疗科室', 1),
    (4, 'DEPT_OBSTETRICS', '妇产科', NULL, 4, '妇产科诊疗科室', 1),
    (5, 'DEPT_OPHTHALMOLOGY', '眼科', NULL, 5, '眼科诊疗科室', 1),
    (6, 'DEPT_ENT', '耳鼻喉科', NULL, 6, '耳鼻喉科诊疗科室', 1),
    (7, 'DEPT_EMERGENCY', '急诊科', NULL, 7, '急诊科24小时服务', 1);
ALTER TABLE his_department ALTER COLUMN main_id SET GENERATED ALWAYS;

-- 2. 修改Doctor表
ALTER TABLE his_doctor ALTER COLUMN main_id SET GENERATED BY DEFAULT;
INSERT INTO his_doctor (main_id, department_main_id, doctor_no, name, gender, title, specialty, phone, email, license_no, status)
VALUES
    -- 内科医生
    (1, 1, 'DOC001', '张伟', 1, '主治医师', '心血管内科', '13800001001', 'zhangwei@hospital.com', 'LIC20230001', 1),
    (2, 1, 'DOC002', '李娜', 0, '副主任医师', '消化内科', '13800001002', 'lina@hospital.com', 'LIC20230002', 1),
    (3, 1, 'DOC003', '王强', 1, '住院医师', '呼吸内科', '13800001003', 'wangqiang@hospital.com', 'LIC20230003', 1),

    -- 外科医生
    (4, 2, 'DOC004', '刘洋', 1, '主任医师', '普外科', '13800002001', 'liuyang@hospital.com', 'LIC20230004', 1),
    (5, 2, 'DOC005', '陈静', 0, '主治医师', '骨科', '13800002002', 'chenjing@hospital.com', 'LIC20230005', 1),

    -- 儿科医生
    (6, 3, 'DOC006', '杨敏', 0, '副主任医师', '儿内科', '13800003001', 'yangmin@hospital.com', 'LIC20230006', 1),
    (7, 3, 'DOC007', '赵杰', 1, '住院医师', '儿外科', '13800003002', 'zhaojie@hospital.com', 'LIC20230007', 1),

    -- 妇产科医生
    (8, 4, 'DOC008', '周婷', 0, '主任医师', '产科', '13800004001', 'zhouting@hospital.com', 'LIC20230008', 1),
    (9, 4, 'DOC009', '吴磊', 1, '主治医师', '妇科', '13800004002', 'wulei@hospital.com', 'LIC20230009', 1),

    -- 眼科医生
    (10, 5, 'DOC010', '郑浩', 1, '副主任医师', '眼视光', '13800005001', 'zhenghao@hospital.com', 'LIC20230010', 1),

    -- 耳鼻喉科医生
    (11, 6, 'DOC011', '孙丽', 0, '主治医师', '耳鼻喉科', '13800006001', 'sunli@hospital.com', 'LIC20230011', 1),

    -- 急诊科医生
    (12, 7, 'DOC012', '钱勇', 1, '住院医师', '急诊内科', '13800007001', 'qianyong@hospital.com', 'LIC20230012', 1),
    (13, 7, 'DOC013', '何娟', 0, '主治医师', '急诊外科', '13800007002', 'hejuan@hospital.com', 'LIC20230013', 1);
ALTER TABLE his_doctor ALTER COLUMN main_id SET GENERATED ALWAYS;

-- 3. 修改Patient表
ALTER TABLE his_patient ALTER COLUMN main_id SET GENERATED BY DEFAULT;
INSERT INTO his_patient (main_id, patient_no, name, gender, birth_date, age, phone, id_card, address, emergency_contact, emergency_phone, blood_type)
VALUES
    (1, 'P202301001', '张小明', 1, '1990-05-15', 33, '13900001001', '110101199005151234', '北京市朝阳区建国路1号', '张父', '13900001002', 'A型'),
    (2, 'P202301002', '李小红', 0, '1985-08-20', 38, '13900002001', '110101198508201234', '北京市海淀区中关村大街2号', '李母', '13900002002', 'B型'),
    (3, 'P202301003', '王大伟', 1, '1992-12-10', 31, '13900003001', '110101199212101234', '北京市西城区金融街3号', '王妻', '13900003002', 'O型'),
    (4, 'P202301004', '刘小芳', 0, '1988-03-25', 35, '13900004001', '110101198803251234', '北京市东城区王府井大街4号', '刘夫', '13900004002', 'AB型'),
    (5, 'P202301005', '陈建国', 1, '1980-07-08', 43, '13900005001', '110101198007081234', '北京市丰台区南四环西路5号', '陈子', '13900005002', 'A型'),
    (6, 'P202301006', '赵美丽', 0, '1995-11-11', 28, '13900006001', '110101199511111234', '北京市石景山区石景山路6号', '赵母', '13900006002', 'O型'),
    (7, 'P202301007', '孙志强', 1, '1983-04-18', 40, '13900007001', '110101198304181234', '北京市海淀区学院路7号', '孙女', '13900007002', 'B型'),
    (8, 'P202301008', '周晓华', 0, '1991-06-22', 32, '13900008001', '110101199106221234', '北京市朝阳区三里屯路8号', '周父', '13900008002', 'A型'),
    (9, 'P202301009', '吴磊', 1, '1987-09-05', 36, '13900009001', '110101198709051234', '北京市东城区东直门内大街9号', '吴妻', '13900009002', 'O型'),
    (10, 'P202301010', '郑雪', 0, '1994-02-14', 30, '13900010001', '110101199402141234', '北京市西城区西单北大街10号', '郑夫', '13900010002', 'AB型');
ALTER TABLE his_patient ALTER COLUMN main_id SET GENERATED ALWAYS;

-- 4. 修改SysUser表
ALTER TABLE his_sysuser ALTER COLUMN main_id SET GENERATED BY DEFAULT;
-- BCrypt密码哈希值对应明文密码 "admin123"
INSERT INTO his_sysuser (main_id, username, password, name, phone, email, role_code, department_main_id, related_id, status, avatar, remark)
VALUES
    -- 管理员
    (1, 'admin', '$2a$12$Na7HMy8Cxvckmeol6hvoVuKPFD6Ob/DX2slGr974WvYnw53XPj3y.', '系统管理员', '13800000001', 'admin@hospital.com', 'ADMIN', NULL, NULL, 1, 'https://avatar.example.com/admin.jpg', '系统管理员账号'),

    -- 医生用户
    (2, 'doctor001', '$2a$12$Na7HMy8Cxvckmeol6hvoVuKPFD6Ob/DX2slGr974WvYnw53XPj3y.', '张伟', '13800001001', 'doctor001@hospital.com', 'DOCTOR', 1, 1, 1, 'https://avatar.example.com/doctor001.jpg', '内科医生'),
    (3, 'doctor002', '$2a$12$Na7HMy8Cxvckmeol6hvoVuKPFD6Ob/DX2slGr974WvYnw53XPj3y.', '李娜', '13800001002', 'doctor002@hospital.com', 'DOCTOR', 1, 2, 1, 'https://avatar.example.com/doctor002.jpg', '内科医生'),
    (4, 'doctor003', '$2a$12$Na7HMy8Cxvckmeol6hvoVuKPFD6Ob/DX2slGr974WvYnw53XPj3y.', '王强', '13800001003', 'doctor003@hospital.com', 'DOCTOR', 1, 3, 1, 'https://avatar.example.com/doctor003.jpg', '内科医生'),
    (5, 'doctor004', '$2a$12$Na7HMy8Cxvckmeol6hvoVuKPFD6Ob/DX2slGr974WvYnw53XPj3y.', '刘洋', '13800002001', 'doctor004@hospital.com', 'DOCTOR', 2, 4, 1, 'https://avatar.example.com/doctor004.jpg', '外科医生'),
    (6, 'doctor005', '$2a$12$Na7HMy8Cxvckmeol6hvoVuKPFD6Ob/DX2slGr974WvYnw53XPj3y.', '陈静', '13800002002', 'doctor005@hospital.com', 'DOCTOR', 2, 5, 1, 'https://avatar.example.com/doctor005.jpg', '外科医生'),
    (7, 'doctor006', '$2a$12$Na7HMy8Cxvckmeol6hvoVuKPFD6Ob/DX2slGr974WvYnw53XPj3y.', '杨敏', '13800003001', 'doctor006@hospital.com', 'DOCTOR', 3, 6, 1, 'https://avatar.example.com/doctor006.jpg', '儿科医生'),
    (8, 'doctor007', '$2a$12$Na7HMy8Cxvckmeol6hvoVuKPFD6Ob/DX2slGr974WvYnw53XPj3y.', '赵杰', '13800003002', 'doctor007@hospital.com', 'DOCTOR', 3, 7, 1, 'https://avatar.example.com/doctor007.jpg', '儿科医生'),
    (9, 'doctor008', '$2a$12$Na7HMy8Cxvckmeol6hvoVuKPFD6Ob/DX2slGr974WvYnw53XPj3y.', '周婷', '13800004001', 'doctor008@hospital.com', 'DOCTOR', 4, 8, 1, 'https://avatar.example.com/doctor008.jpg', '妇产科医生'),
    (10, 'doctor009', '$2a$12$Na7HMy8Cxvckmeol6hvoVuKPFD6Ob/DX2slGr974WvYnw53XPj3y.', '吴磊', '13800004002', 'doctor009@hospital.com', 'DOCTOR', 4, 9, 1, 'https://avatar.example.com/doctor009.jpg', '妇科医生'),
    (11, 'doctor010', '$2a$12$Na7HMy8Cxvckmeol6hvoVuKPFD6Ob/DX2slGr974WvYnw53XPj3y.', '郑浩', '13800005001', 'doctor010@hospital.com', 'DOCTOR', 5, 10, 1, 'https://avatar.example.com/doctor010.jpg', '眼科医生'),
    (12, 'doctor011', '$2a$12$Na7HMy8Cxvckmeol6hvoVuKPFD6Ob/DX2slGr974WvYnw53XPj3y.', '孙丽', '13800006001', 'doctor011@hospital.com', 'DOCTOR', 6, 11, 1, 'https://avatar.example.com/doctor011.jpg', '耳鼻喉科医生'),
    (13, 'doctor012', '$2a$12$Na7HMy8Cxvckmeol6hvoVuKPFD6Ob/DX2slGr974WvYnw53XPj3y.', '钱勇', '13800007001', 'doctor012@hospital.com', 'DOCTOR', 7, 12, 1, 'https://avatar.example.com/doctor012.jpg', '急诊内科医生'),
    (14, 'doctor013', '$2a$12$Na7HMy8Cxvckmeol6hvoVuKPFD6Ob/DX2slGr974WvYnw53XPj3y.', '何娟', '13800007002', 'doctor013@hospital.com', 'DOCTOR', 7, 13, 1, 'https://avatar.example.com/doctor013.jpg', '急诊外科医生'),

    -- 护士用户
    (15, 'nurse001', '$2a$12$Na7HMy8Cxvckmeol6hvoVuKPFD6Ob/DX2slGr974WvYnw53XPj3y.', '护士长王芳', '13800000101', 'nurse001@hospital.com', 'NURSE', 1, NULL, 1, 'https://avatar.example.com/nurse001.jpg', '护士长'),
    (16, 'nurse002', '$2a$12$Na7HMy8Cxvckmeol6hvoVuKPFD6Ob/DX2slGr974WvYnw53XPj3y.', '护士李丽', '13800000102', 'nurse002@hospital.com', 'NURSE', 1, NULL, 1, 'https://avatar.example.com/nurse002.jpg', '值班护士'),

    -- 药师用户
    (17, 'pharmacist001', '$2a$12$Na7HMy8Cxvckmeol6hvoVuKPFD6Ob/DX2slGr974WvYnw53XPj3y.', '主任药师赵敏', '13800000201', 'pharmacist001@hospital.com', 'PHARMACIST', NULL, NULL, 1, 'https://avatar.example.com/pharmacist001.jpg', '药房主任'),

    -- 收费员用户
    (18, 'cashier001', '$2a$12$Na7HMy8Cxvckmeol6hvoVuKPFD6Ob/DX2slGr974WvYnw53XPj3y.', '收费员孙磊', '13800000301', 'cashier001@hospital.com', 'CASHIER', NULL, NULL, 1, 'https://avatar.example.com/cashier001.jpg', '收费员');
ALTER TABLE his_sysuser ALTER COLUMN main_id SET GENERATED ALWAYS;

-- 5. 修改Medicine表
ALTER TABLE his_medicine ALTER COLUMN main_id SET GENERATED BY DEFAULT;
INSERT INTO his_medicine (main_id, medicine_code, name, generic_name, specification, dosage_form, manufacturer, category, unit, retail_price, purchase_price, stock_quantity, min_stock, max_stock, is_prescription, approval_no, status)
VALUES
    -- 退烧药
    (1, 'MED001', '对乙酰氨基酚片', '对乙酰氨基酚', '0.5g*10片/盒', '片剂', '制药公司A', '解热镇痛药', '盒', 15.00, 10.00, 500, 100, 1000, 0, '国药准字H12345678', 1),
    (2, 'MED002', '布洛芬缓释胶囊', '布洛芬', '0.3g*24粒/盒', '胶囊剂', '制药公司B', '解热镇痛药', '盒', 25.00, 18.00, 300, 50, 600, 1, '国药准字H12345679', 1),
    (3, 'MED003', '阿司匹林肠溶片', '阿司匹林', '100mg*100片/瓶', '片剂', '制药公司C', '抗血小板药', '瓶', 8.00, 5.00, 200, 50, 500, 0, '国药准字H12345680', 1),

    -- 抗生素
    (4, 'MED004', '阿莫西林胶囊', '阿莫西林', '0.25g*24粒/盒', '胶囊剂', '制药公司D', '抗生素', '盒', 12.00, 8.00, 400, 100, 800, 1, '国药准字H12345681', 1),
    (5, 'MED005', '头孢拉定胶囊', '头孢拉定', '0.25g*24粒/盒', '胶囊剂', '制药公司E', '抗生素', '盒', 28.00, 20.00, 350, 80, 700, 1, '国药准字H12345682', 1),
    (6, 'MED006', '盐酸左氧氟沙星片', '左氧氟沙星', '0.5g*10片/盒', '片剂', '制药公司F', '抗生素', '盒', 35.00, 25.00, 250, 50, 500, 0, '国药准字H12345683', 1),

    -- 感冒药
    (7, 'MED007', '复方氨酚烷胺片', '复方氨酚烷胺', '10片/盒', '片剂', '制药公司G', '感冒药', '盒', 18.00, 12.00, 600, 150, 1200, 0, '国药准字H12345684', 1),
    (8, 'MED008', '板蓝根颗粒', '板蓝根', '10g*10袋/盒', '颗粒剂', '制药公司H', '感冒药', '盒', 20.00, 15.00, 400, 100, 800, 0, '国药准字H12345685', 1),

    -- 胃肠药
    (9, 'MED009', '蒙脱石散', '蒙脱石', '3g/袋', '散剂', '制药公司I', '胃肠药', '袋', 12.00, 8.00, 800, 200, 1500, 0, '国药准字H12345686', 1),
    (10, 'MED010', '多潘立酮片', '多潘立酮', '10mg*30片/盒', '片剂', '制药公司J', '胃肠药', '盒', 22.00, 15.00, 300, 80, 600, 0, '国药准字H12345687', 1),

    -- 心血管药
    (11, 'MED011', '硝苯地平控释片', '硝苯地平', '30mg*7片/盒', '片剂', '制药公司K', '心血管药', '盒', 45.00, 30.00, 200, 50, 400, 0, '国药准字H12345688', 1),
    (12, 'MED012', '阿托伐他汀钙片', '阿托伐他汀', '20mg*7片/盒', '片剂', '制药公司L', '心血管药', '盒', 55.00, 40.00, 150, 30, 300, 0, '国药准字H12345689', 1),

    -- 消化系统药
    (13, 'MED013', '奥美拉唑肠溶胶囊', '奥美拉唑', '20mg*14粒/盒', '胶囊剂', '制药公司M', '消化系统药', '盒', 38.00, 25.00, 180, 60, 360, 0, '国药准字H12345690', 1),
    (14, 'MED014', '多酶片', '多酶', '100片/瓶', '片剂', '制药公司N', '消化系统药', '瓶', 28.00, 18.00, 220, 70, 440, 0, '国药准字H12345691', 1),

    -- 维生素
    (15, 'MED015', '维生素C片', '维生素C', '0.1g*100片/瓶', '片剂', '制药公司O', '维生素', '瓶', 8.00, 5.00, 500, 150, 1000, 0, '国药准字H12345692', 1),
    (16, 'MED016', '维生素B族片', '维生素B族', '100片/瓶', '片剂', '制药公司P', '维生素', '瓶', 12.00, 8.00, 350, 100, 700, 0, '国药准字H12345693', 1),

    -- 中成药
    (17, 'MED017', '连花清瘟胶囊', '连花清瘟', '24粒/盒', '胶囊剂', '中药公司A', '感冒药', '盒', 30.00, 22.00, 450, 120, 900, 0, '国药准字H12345694', 1),
    (18, 'MED018', '急支糖浆', '急支糖浆', '100ml/瓶', '糖浆剂', '中药公司B', '感冒药', '瓶', 25.00, 18.00, 300, 100, 600, 0, '国药准字H12345695', 1),
    (19, 'MED019', '川贝枇杷膏', '川贝枇杷', '100g/瓶', '煎膏剂', '中药公司C', '止咳药', '瓶', 45.00, 30.00, 200, 60, 400, 0, '国药准字H12345696', 1),

    -- 消毒液
    (20, 'MED020', '碘伏消毒液', '碘伏', '100ml/瓶', '外用液体', '制药公司Q', '消毒用品', '瓶', 10.00, 6.00, 1000, 200, 2000, 0, '国药准字H12345697', 1),
    (21, 'MED021', '75%医用酒精', '医用酒精', '500ml/瓶', '外用液体', '制药公司R', '消毒用品', '瓶', 8.00, 5.00, 1200, 300, 2400, 0, '国药准字H12345698', 1);
ALTER TABLE his_medicine ALTER COLUMN main_id SET GENERATED ALWAYS;

-- 6. 修改Registration表
ALTER TABLE his_registration ALTER COLUMN main_id SET GENERATED BY DEFAULT;
INSERT INTO his_registration (main_id, patient_main_id, department_main_id, doctor_main_id, reg_no, visit_date, visit_type, registration_fee, queue_no, status)
VALUES
    -- 今天已挂号的患者
    (1, 1, 1, 1, 'REG20230103001', CURRENT_DATE, 1, 50.00, 'A001', 2),
    (2, 2, 1, 2, 'REG20230103002', CURRENT_DATE, 1, 50.00, 'A002', 2),
    (3, 3, 2, 4, 'REG20230103003', CURRENT_DATE, 2, 100.00, 'B001', 2),
    (4, 4, 3, 6, 'REG20230103004', CURRENT_DATE, 1, 50.00, 'A003', 2),
    (5, 5, 4, 8, 'REG20230103005', CURRENT_DATE, 2, 100.00, 'B002', 2),

    -- 已就诊的挂号
    (6, 6, 1, 1, 'REG20230102001', CURRENT_DATE - INTERVAL '1 day', 1, 50.00, 'A005', 3),
    (7, 7, 3, 6, 'REG20230102002', CURRENT_DATE - INTERVAL '1 day', 1, 50.00, 'A006', 3),
    (8, 8, 4, 8, 'REG20230102003', CURRENT_DATE - INTERVAL '1 day', 2, 100.00, 'B003', 3),
    (9, 9, 2, 4, 'REG20230102004', CURRENT_DATE - INTERVAL '1 day', 1, 50.00, 'A007', 3),
    (10, 10, 5, 10, 'REG20230102005', CURRENT_DATE - INTERVAL '1 day', 1, 50.00, 'A008', 3);
ALTER TABLE his_registration ALTER COLUMN main_id SET GENERATED ALWAYS;

-- 7. 修改MedicalRecord表
ALTER TABLE his_medical_record ALTER COLUMN main_id SET GENERATED BY DEFAULT;
INSERT INTO his_medical_record (main_id, registration_main_id, patient_main_id, doctor_main_id, record_no, visit_time, chief_complaint, diagnosis, diagnosis_code, treatment_plan, status)
VALUES
    (1, 6, 6, 1, 'REC20230102001', CURRENT_TIMESTAMP - INTERVAL '1 day', '发热、咳嗽3天', '上呼吸道感染', 'J06.9', '开处方药、多喝水、注意休息', 1),
    (2, 7, 7, 3, 'REC20230102002', CURRENT_TIMESTAMP - INTERVAL '1 day', '腹痛、恶心1天', '急性胃肠炎', 'K59.0', '禁食、补液、开处方药', 1),
    (3, 8, 8, 5, 'REC20230102003', CURRENT_TIMESTAMP - INTERVAL '1 day', '眼痛、流泪2天', '结膜炎', 'H10.1', '开眼药水、注意用眼卫生', 1),
    (4, 9, 9, 2, 'REC20230102004', CURRENT_TIMESTAMP - INTERVAL '1 day', '外伤后肿痛1天', '软组织挫伤', 'S06.0', '冷敷、止痛药、观察', 1),
    (5, 10, 10, 6, 'REC20230102005', CURRENT_TIMESTAMP - INTERVAL '1 day', '咽痛、吞咽困难2天', '急性咽炎', 'J02.9', '抗感染治疗、注意饮食', 1);
ALTER TABLE his_medical_record ALTER COLUMN main_id SET GENERATED ALWAYS;

-- 8. 修改Prescription表
ALTER TABLE his_prescription ALTER COLUMN main_id SET GENERATED BY DEFAULT;
INSERT INTO his_prescription (main_id, record_main_id, patient_main_id, doctor_main_id, prescription_no, prescription_type, total_amount, item_count, status, validity_days)
VALUES
    -- 已开处方
    (1, 1, 6, 1, 'PRE20230102001', 1, 45.00, 2, 3, 3),
    (2, 2, 7, 3, 'PRE20230102002', 1, 85.00, 3, 3, 3),
    (3, 3, 8, 5, 'PRE20230102003', 1, 80.00, 2, 3, 3),
    (4, 4, 9, 2, 'PRE20230102004', 1, 50.00, 2, 3, 3),
    (5, 5, 10, 6, 'PRE20230102005', 1, 38.00, 2, 3, 3),

    -- 今天已开处方
    (6, 1, 1, 1, 'PRE20230103001', 1, 52.00, 3, 2, 3),
    (7, 2, 2, 2, 'PRE20230103002', 1, 68.00, 3, 2, 3),
    (8, 3, 3, 4, 'PRE20230103003', 1, 90.00, 4, 2, 3);
ALTER TABLE his_prescription ALTER COLUMN main_id SET GENERATED ALWAYS;

-- 9. 修改PrescriptionDetail表
ALTER TABLE his_prescription_detail ALTER COLUMN main_id SET GENERATED BY DEFAULT;
INSERT INTO his_prescription_detail (main_id, prescription_main_id, medicine_main_id, medicine_name, unit_price, quantity, subtotal, specification, unit, frequency, dosage, route, days, instructions, sort_order)
VALUES
    -- 处方1: 发热、咳嗽 (对乙酰氨基酚 + 阿莫西林)
    (1, 1, 1, '对乙酰氨基酚片', 15.00, 1, 15.00, '0.5g', '盒', 'tid', '0.5g/次,3次/日', '口服', 3, '饭后服用,体温超过38.5℃时使用', 1),
    (2, 1, 4, '阿莫西林胶囊', 12.00, 2, 24.00, '0.25g', '盒', 'qid', '0.25g/次,3次/日', '口服', 3, '饭后服用,服用期间禁酒', 2),

    -- 处方2: 腹痛、恶心 (蒙脱石散 + 多潘立酮)
    (3, 2, 9, '蒙脱石散', 12.00, 2, 24.00, '3g', '袋', 'tid', '1袋/次,3次/日', '口服', 3, '饭前1小时服用', 1),
    (4, 2, 10, '多潘立酮片', 22.00, 1, 22.00, '10mg', '盒', 'tid', '1片/次,3次/日', '口服', 3, '饭前30分钟服用', 2),

    -- 处方3: 眼痛、流泪 (左氧氟沙星 + 眼药水)
    (5, 3, 6, '盐酸左氧氟沙星片', 35.00, 1, 35.00, '0.5g', '盒', 'qid', '1片/次,3次/日', '口服', 5, '饭后服用,注意防晒', 1),
    (6, 3, 20, '碘伏消毒液', 10.00, 1, 10.00, '100ml', '瓶', 'prn', '外用', '外用', 7, '每日3次清洁眼部', 2),

    -- 处方4: 软组织挫伤 (布洛芬 + 外用药)
    (7, 4, 2, '布洛芬缓释胶囊', 25.00, 1, 25.00, '0.3g', '盒', 'bid', '1粒/次,2次/日', '口服', 3, '饭后服用,温水送服', 1),
    (8, 4, 20, '碘伏消毒液', 10.00, 2, 20.00, '100ml', '瓶', 'prn', '外用', '外用', 7, '每日3次清洁患处', 2),

    -- 处方5: 咽痛 (急支糖浆 + 蒙脱石散)
    (9, 5, 2, '布洛芬缓释胶囊', 25.00, 1, 25.00, '0.3g', '盒', 'prn', '1粒/次,2次/日', '口服', 3, '饭后服用', 1),
    (10, 5, 18, '急支糖浆', 25.00, 2, 50.00, '100ml', '瓶', 'tid', '10ml/次,3次/日', '口服', 3, '饭后服用', 2),

    -- 处方6: 发热、咳嗽 (对乙酰氨基酚 + 连花清瘟)
    (11, 6, 1, '对乙酰氨基酚片', 15.00, 2, 30.00, '0.5g', '盒', 'prn', '1片/次,4次/日', '口服', 3, '体温超过38.5℃时服用', 1),
    (12, 6, 17, '连花清瘟胶囊', 30.00, 2, 60.00, '24粒', '盒', 'tid', '2粒/次,3次/日', '口服', 3, '饭后服用,儿童减半', 2),

    -- 处方7: 腹痛、恶心 (奥美拉唑 + 阿莫西林)
    (13, 7, 13, '奥美拉唑肠溶胶囊', 38.00, 1, 38.00, '20mg', '盒', 'qd', '1粒/次,1次/日', '口服', 3, '早餐前30分钟服用', 1),
    (14, 7, 4, '阿莫西林胶囊', 12.00, 2, 24.00, '0.25g', '盒', 'tid', '2粒/次,3次/日', '口服', 3, '饭后服用,服用期间禁酒', 2),
    (15, 7, 9, '蒙脱石散', 12.00, 1, 12.00, '3g', '袋', 'tid', '1袋/次,3次/日', '口服', 3, '饭前1小时服用', 3),

    -- 处方8: 眼病 (左氧氟沙星)
    (16, 8, 6, '盐酸左氧氟沙星片', 35.00, 1, 35.00, '0.5g', '盒', 'qid', '1片/次,3次/日', '口服', 5, '注意防晒,避免强光刺激', 1),
    (17, 8, 20, '碘伏消毒液', 10.00, 2, 20.00, '100ml', '瓶', 'prn', '外用', '外用', 7, '每日3次清洁眼部', 2);
ALTER TABLE his_prescription_detail ALTER COLUMN main_id SET GENERATED ALWAYS;

-- 10. 修改Charge表
ALTER TABLE his_charge ALTER COLUMN main_id SET GENERATED BY DEFAULT;
INSERT INTO his_charge (main_id, patient_main_id, charge_no, charge_type, total_amount, actual_amount, registration_main_id, prescription_main_id, payment_method, transaction_no, status, cashier_main_id, operator_id, charge_time, remark)
VALUES
    -- 已缴费的挂号费
    (1, 1, 'CHA20230103001', 1, 50.00, 50.00, 1, NULL, 3, 'TXN202301030001', 1, 18, 1, CURRENT_TIMESTAMP, '挂号费'),
    (2, 2, 'CHA20230103002', 1, 50.00, 50.00, 2, NULL, 3, 'TXN202301030002', 1, 18, 2, CURRENT_TIMESTAMP, '挂号费'),
    (3, 3, 'CHA20230103003', 2, 100.00, 100.00, 3, NULL, 3, 'TXN202301030003', 1, 18, 1, CURRENT_TIMESTAMP, '挂号费(专家号)'),
    (4, 4, 'CHA20230103004', 1, 50.00, 50.00, 4, NULL, 3, 'TXN202301030004', 1, 16, 15, CURRENT_TIMESTAMP, '挂号费'),
    (5, 5, 'CHA20230103005', 2, 100.00, 100.00, 5, NULL, 3, 'TXN202301030005', 1, 16, 8, CURRENT_TIMESTAMP, '挂号费(专家号)'),

    -- 已缴费的药费
    (6, 6, 'CHA20230102001', 2, 45.00, 45.00, NULL, 1, 3, 'TXN202301020001', 1, 17, 2, CURRENT_TIMESTAMP - INTERVAL '1 day', '处方药费'),
    (7, 7, 'CHA20230102002', 2, 85.00, 85.00, NULL, 2, 3, 'TXN202301020002', 1, 17, 2, CURRENT_TIMESTAMP - INTERVAL '1 day', '处方药费'),
    (8, 8, 'CHA20230102003', 2, 80.00, 80.00, NULL, 3, 3, 'TXN202301020003', 1, 17, 3, CURRENT_TIMESTAMP - INTERVAL '1 day', '处方药费'),
    (9, 9, 'CHA20230102004', 2, 50.00, 50.00, NULL, 4, 3, 'TXN202301020004', 1, 18, 9, CURRENT_TIMESTAMP - INTERVAL '1 day', '处方药费'),
    (10, 10, 'CHA20230102005', 2, 38.00, 38.00, NULL, 5, 3, 'TXN202301020005', 1, 18, 10, CURRENT_TIMESTAMP - INTERVAL '1 day', '处方药费'),

    -- 今天的处方缴费
    (11, 1, 'CHA20230103006', 2, 52.00, 52.00, NULL, 6, 3, 'TXN202301030006', 1, 18, 1, CURRENT_TIMESTAMP, '处方药费'),
    (12, 2, 'CHA20230103007', 2, 68.00, 68.00, NULL, 7, 3, 'TXN202301030007', 1, 18, 2, CURRENT_TIMESTAMP, '处方药费'),
    (13, 3, 'CHA20230103008', 2, 90.00, 90.00, NULL, 8, 3, 'TXN202301030008', 1, 18, 1, CURRENT_TIMESTAMP, '处方药费');
ALTER TABLE his_charge ALTER COLUMN main_id SET GENERATED ALWAYS;

-- ================================================================================
-- 序列重置 - 同步所有 IDENTITY 列的序列值
-- ================================================================================
-- 由于测试数据手动指定了主键ID，需要将所有表的序列重置到当前最大值+1
-- 避免后续插入数据时出现主键冲突错误
-- ================================================================================

DO $$
DECLARE
    table_name text;
    max_id bigint;
    seq_name text;
BEGIN
    -- 定义需要重置序列的表及其主键列
    FOR table_name IN VALUES
        ('his_department'),
        ('his_doctor'),
        ('his_patient'),
        ('his_sysuser'),
        ('his_medicine'),
        ('his_registration'),
        ('his_medical_record'),
        ('his_prescription'),
        ('his_prescription_detail'),
        ('his_charge')
    LOOP
        -- 获取当前表的最大主键ID
        EXECUTE format(
            'SELECT COALESCE(MAX(main_id), 0) FROM %I',
            table_name
        ) INTO max_id;

        -- 获取序列名称
        EXECUTE format(
            'SELECT pg_get_serial_sequence(%L, %L)',
            table_name, 'main_id'
        ) INTO seq_name;

        -- 重置序列到最大ID+1
        IF seq_name IS NOT NULL THEN
            EXECUTE format(
                'SELECT setval(%L, %L, false)',
                seq_name, max_id + 1
            );
            RAISE NOTICE '已重置表 % 的序列，当前最大ID: %，下一个值: %',
                table_name, max_id, max_id + 1;
        ELSE
            RAISE WARNING '表 % 没有找到序列', table_name;
        END IF;
    END LOOP;
END $$;

-- 验证序列重置结果
DO $$
DECLARE
    table_name text;
    seq_name text;
    next_val bigint;
    max_id bigint;
BEGIN
    RAISE NOTICE '========================================';
    RAISE NOTICE '序列重置验证结果';
    RAISE NOTICE '========================================';

    FOR table_name IN VALUES
        ('his_department'),
        ('his_doctor'),
        ('his_patient'),
        ('his_sysuser'),
        ('his_medicine'),
        ('his_registration'),
        ('his_medical_record'),
        ('his_prescription'),
        ('his_prescription_detail'),
        ('his_charge')
    LOOP
        -- 获取序列名称
        EXECUTE format(
            'SELECT pg_get_serial_sequence(%L, %L)',
            table_name, 'main_id'
        ) INTO seq_name;

        IF seq_name IS NOT NULL THEN
            -- 获取下一个序列值
            EXECUTE format(
                'SELECT nextval(%L)',
                seq_name
            ) INTO next_val;

            -- 由于nextval会推进序列，需要回退以便使用
            EXECUTE format(
                'SELECT setval(%L, %L, true)',
                seq_name, next_val - 1
            );

            -- 获取当前最大ID
            EXECUTE format(
                'SELECT COALESCE(MAX(main_id), 0) FROM %I',
                table_name
            ) INTO max_id;

            RAISE NOTICE '%: 最大ID=%, 下一个序列值=%',
                table_name, max_id, next_val;
        END IF;
    END LOOP;

    RAISE NOTICE '========================================';
    RAISE NOTICE '序列重置完成！现在可以安全插入新数据';
    RAISE NOTICE '========================================';
END $$;

-- ================================================================================
-- 迁移完成
-- ================================================================================
-- 所有测试数据已成功插入到数据库中
--
-- 测试账号信息:
-- - 管理员: admin / admin123
-- - 医生: doctor001 ~ doctor013 / admin123
-- - 护士: nurse001 ~ nurse002 / admin123
-- - 药师: pharmacist001 / admin123
-- - 收费员: cashier001 / admin123
--
-- 数据统计:
-- - 系统用户: 18个
-- - 科室: 7个
-- - 医生: 13个
-- - 患者: 10个
-- - 药品: 21个
-- - 挂号: 10个
-- - 病历: 5个
-- - 处方: 8个
-- - 处方明细: 21个
-- - 收费: 13个
--
-- 重要提示:
-- - 所有表的 IDENTITY 序列已自动重置到最大主键ID+1
-- - 现在可以安全地通过应用程序插入新数据，不会出现主键冲突
-- - 如果需要重新加载此脚本，请先清空相关表的数据
-- ================================================================================
